### ISSUE TITLE
Percentage-based RNG

### ISSUE THREAD

**Issue by benjamin-allen** [Nullsrc/nuctex#9]
For combat AI, as needed in #4, it would be beneficial to have an RNG function that is passed a decimal value that represents a percentage chance. Another function that works with integers in a similar would be useful.

**Comment by nanovad** [comment]
An alternative would be to pass it a single argument indicating a 1 in arg chance.

**Comment by benjamin-allen** [comment]
My thought is to have a function crng(float) that takes its argument as a raw chance that it will return zero. Passing it .25 will return 0 1/4 times, passing it .5 will return 0 half of the time, etc. The integer one would be rather redundant; it's mostly just a frontend difference.

Your concept would be useful as well, although the best implementation would probably be one that takes arguments x and y and then has an x/y chance to return 0. It's also rather redundant, as approximations could be done with the crng() system, but it's something to look into.

**Comment by benjamin-allen** [comment]
Turns out that the fractional rng (which has been implemented as crng(int, int) is perfectly acceptable as a percentage-based rng. If a 1/x chance needs to happen, one can call the zrng(int) (now renamed arng(int)) and check it against 0, which is how crng is intended to be used as well.
